-- ============================================================
-- Revera Clinics - FULL DATABASE MIGRATION SCRIPT
-- Paste this entire file into your new Supabase SQL Editor
-- and run it once. It is fully idempotent (safe to re-run).
--
-- Tables created (in dependency order):
--   1.  extensions
--   2.  branches
--   3.  categories
--   4.  services
--   5.  providers
--   6.  provider_attendance
--   7.  customers
--   8.  reservations
--   9.  rooms
--   10. service_rooms (junction)
--   11. page_settings
--   12. roles
--   13. employee_accounts
--
-- Seed data included for:
--   branches, categories, services, rooms, service_rooms, roles
--
-- After running this script you MUST manually:
--   1. Create your admin user via Supabase Dashboard -> Authentication -> Users
--   2. Run the "Link Admin User" block at the bottom with the new user UUID.
-- ============================================================


-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- 1. BRANCHES
CREATE TABLE IF NOT EXISTS public.branches (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name_en     text        NOT NULL,
  name_ar     text        NOT NULL,
  address_en  text        NOT NULL,
  address_ar  text        NOT NULL,
  phone       text,
  maps_embed  text,
  maps_link   text,
  status      text        NOT NULL DEFAULT 'active',
  sort_order  integer     NOT NULL DEFAULT 0,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);
ALTER TABLE public.branches DISABLE ROW LEVEL SECURITY;

INSERT INTO public.branches (name_en, name_ar, address_en, address_ar, phone, maps_embed, maps_link, status, sort_order)
VALUES
  (
    'New Cairo Branch',
    'فرع القاهرة الجديدة',
    'Tagamoa, New Cairo, Cairo',
    'التجمع الخامس، القاهرة الجديدة، القاهرة',
    '+201035595691',
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3455.240762823598!2d31.451330111694702!3d30.001242420510955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x145823da15b7dca9%3A0xb388d9b9c32ebce5!2sRevera%20Clinic%20-%20Tagamoa%20Branch!5e0!3m2!1sen!2sit!4v1781634264961!5m2!1sen!2sit',
    'https://maps.app.goo.gl/sXQXDW3A7DdZSRJZ9',
    'active', 0
  ),
  (
    'Sheikh Zayed Branch',
    'فرع الشيخ زايد',
    'El Nada Clinics Complex, Sheikh Zayed, Giza',
    'مجمع عيادات الندى، الشيخ زايد، الجيزة',
    '+201023122323',
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3452.9529642711104!2d30.9335256!3d30.066882699999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x145859626e72e263%3A0x148f1e87e5c115c0!2sEl%20nada%20CLINICS%20complex!5e0!3m2!1sen!2sit!4v1781634456678!5m2!1sen!2sit',
    'https://maps.app.goo.gl/7ig2Q9iCY9uszyHq9',
    'active', 1
  )
ON CONFLICT DO NOTHING;


-- 2. CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  key        text    PRIMARY KEY,
  en         text    NOT NULL,
  ar         text    NOT NULL,
  sort_order integer DEFAULT 0
);
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;

INSERT INTO public.categories (key, en, ar, sort_order) VALUES
  ('dermatology',   'Dermatology & Aesthetic',  'الجلدية والتجميل',      0),
  ('gynecology',    'Gynecology',               'النساء والتوليد',        1),
  ('physiotherapy', 'Physical Therapy',         'العلاج الطبيعي',         2),
  ('osteopathy',    'Osteopathy & Nutrition',   'تقويم العظام والتغذية',  3)
ON CONFLICT (key) DO NOTHING;


-- 3. SERVICES
CREATE TABLE IF NOT EXISTS public.services (
  id              bigint      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  en              text        NOT NULL,
  ar              text        NOT NULL,
  img             text,
  cat             text,
  unit            text,
  price           numeric     NOT NULL DEFAULT 0,
  duration        text,
  description_en  text,
  description_ar  text,
  is_shared       boolean     NOT NULL DEFAULT false,
  enable_reminder boolean     NOT NULL DEFAULT true,
  branch_pricing  jsonb       NOT NULL DEFAULT '{}'::jsonb,
  sort_order      integer     NOT NULL DEFAULT 0,
  visible         boolean     NOT NULL DEFAULT true,
  active          boolean     NOT NULL DEFAULT true,
  created_at      timestamptz DEFAULT now()
);
ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;

INSERT INTO public.services (id, en, ar, img, cat, unit, price, sort_order)
OVERRIDING SYSTEM VALUE VALUES
  (1,  'Skin Dermatology Clinics',                   'عيادات الجلدية',                      '/images/services/dermatology-service/dermatology.jpeg',         'dermatology',   'session', 100, 0),
  (2,  'Skin Care Treatments',                       'تجميل البشرة',                        '/images/services/dermatology-service/skincare-treatment.jpg',    'dermatology',   'session', 120, 1),
  (3,  'Skin Care Sessions',                         'جلسات العناية بالبشرة',               '/images/services/dermatology-service/skincare-session.webp',     'dermatology',   'session',  80, 2),
  (4,  'Hair & Scalp Treat',                         'علاج الشعر والتساقط',                 '/images/services/dermatology-service/hair-scalp-treatment.jpg',  'dermatology',   'session',  90, 3),
  (5,  'Laser Hair Removal',                         'إزالة الشعر بالليزر (رجالي ونسائي)', '/images/services/dermatology-service/laser-hair-removal.jpg',    'dermatology',   'session', 150, 4),
  (6,  'Therapeutic Laser',                          'الليزر العلاجي',                      '/images/services/dermatology-service/therapeutic-laser.jpg',     'dermatology',   'session', 110, 5),
  (7,  'Aesthetic Injections (Botox/Filler/Plasma)', 'حقن تجميلية (بوتوكس/فيلر/بلازما)',   '/images/services/dermatology-service/aesthetic-injections.jpg', 'dermatology',   'session', 250, 6),
  (11, 'Gynecology Clinics',                         'النساء والتوليد',                     '/images/services/gyna-service/gyna.jpg',                         'gynecology',    'session', 150, 0),
  (12, 'Pregnancy Follow-Up',                        'متابعة الحمل',                        '/images/services/gyna-service/pregnancy-followup.webp',          'gynecology',    'session', 130, 1),
  (13, 'Infertility & Fertility Treatment',          'علاج العقم وتأخر الإنجاب',            '/images/services/gyna-service/infertility.avif',                 'gynecology',    'session', 200, 2),
  (14, 'Women''s Aesthetic Treatments',              'التجميل النسائي',                     '/images/services/gyna-service/women-aethetic-treatment.webp',    'gynecology',    'session', 180, 3),
  (15, 'Laser Vaginal Rejuvenation',                 'ليزر تجديد المهبل',                   '/images/services/gyna-service/laser-vaginal-rejuvenation.jpg',   'gynecology',    'session', 220, 4),
  (16, 'Vaginal Tightening',                         'شد المهبل (Tightening)',              '/images/services/gyna-service/vaginal-tightening.jpg',           'gynecology',    'session', 190, 5),
  (17, 'Marital & Family Counseling',                'الاستشارات الزوجية والأسرية',         '/images/services/gyna-service/consultation.jpg',                 'gynecology',    'session', 100, 6),
  (21, 'Physical Therapy',                           'العلاج الطبيعي',                      '/images/services/physicaltherapy_service/physical-therapy.jpg',  'physiotherapy', 'session',  70, 0),
  (22, 'Rehabilitation',                             'إعادة التأهيل',                       '/images/services/physicaltherapy_service/rehab.jpg',             'physiotherapy', 'session',  80, 1),
  (23, 'Posture & Motion Improvement',               'تحسين القوام والحركة',                '/images/services/physicaltherapy_service/posture.webp',          'physiotherapy', 'session',  75, 2),
  (31, 'Osteopathy',                                 'تقويم العظام',                        '/images/services/nutrition_service/osteopathy.jpg',               'osteopathy',    'session',  90, 0),
  (32, 'Therapeutic Nutrition',                      'التغذية العلاجية',                    '/images/services/nutrition_service/therapeutic-diet.png',         'osteopathy',    'session',  85, 1),
  (33, 'Weight Loss Programs',                       'برامج إنقاص الوزن',                  '/images/services/nutrition_service/weight-loss.jpg',              'osteopathy',    'session',  95, 2),
  (34, 'Body Contouring & Shaping',                  'تنسيق القوام',                        '/images/services/nutrition_service/body-contouring.jpg',          'osteopathy',    'session', 110, 3)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.services','id'), GREATEST((SELECT MAX(id) FROM public.services), 1));


-- 4. PROVIDERS (DOCTORS)
CREATE TABLE IF NOT EXISTS public.providers (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text        NOT NULL,
  bookings_count      integer     NOT NULL DEFAULT 0,
  services            jsonb       NOT NULL DEFAULT '[]'::jsonb,
  more_count          integer     NOT NULL DEFAULT 0,
  rating              numeric     NOT NULL DEFAULT 0,
  image               text,
  phone               text,
  gender              text        CHECK (gender IN ('Male', 'Female')),
  age                 integer,
  specialty           text,
  national_id         text,
  working_days_hours  jsonb,
  branch_id           uuid        REFERENCES public.branches(id) ON DELETE SET NULL,
  start_date          date,
  created_at          timestamptz DEFAULT now()
);
ALTER TABLE public.providers DISABLE ROW LEVEL SECURITY;

INSERT INTO public.providers (name, bookings_count, services, more_count, rating) VALUES
  ('Dr. Ahmed Medhat',  0, '["Tattoo Removal (Small)", "Tattoo Removal (Medium)"]'::jsonb,             4, 0),
  ('Dr. Radwa Seif',    0, '["Physio: Basic Relief (3)", "Physio: Standard Recovery (6)"]'::jsonb,      4, 0),
  ('Dr. Sara El Gamel', 1, '["Half Arm", "Full Arms"]'::jsonb,                                         14, 0)
ON CONFLICT DO NOTHING;


-- 5. PROVIDER ATTENDANCE
CREATE TABLE IF NOT EXISTS public.provider_attendance (
  id           uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id  uuid  REFERENCES public.providers(id) ON DELETE CASCADE,
  date         date  NOT NULL,
  status       text  NOT NULL CHECK (status IN ('Present', 'Absent', 'On Leave')),
  check_in     time,
  check_out    time,
  notes        text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now(),
  UNIQUE(provider_id, date)
);
ALTER TABLE public.provider_attendance DISABLE ROW LEVEL SECURITY;


-- 6. CUSTOMERS
CREATE TABLE IF NOT EXISTS public.customers (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text        NOT NULL,
  mobile              text        NOT NULL UNIQUE,
  gender              text        CHECK (gender IN ('Male', 'Female')),
  email               text,
  number_of_bookings  integer     DEFAULT 0,
  registration_date   timestamptz DEFAULT now(),
  active              boolean     DEFAULT true,
  spent_amount        numeric     DEFAULT 0,
  outstanding         numeric     DEFAULT 0,
  area                text,
  location_name       text,
  street_name         text,
  building_no         text,
  floor_no            text,
  note                text,
  age                 integer,
  national_id         text,
  address             text,
  referral            text,
  occupation          text,
  created_at          timestamptz DEFAULT now(),
  updated_at          timestamptz DEFAULT now()
);
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;


-- 7. RESERVATIONS
CREATE TABLE IF NOT EXISTS public.reservations (
  id              uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id      bigint,
  date            text    NOT NULL,
  requested_time  text,
  name            text,
  email           text,
  phone           text,
  notes           text    DEFAULT '',
  status          text    NOT NULL DEFAULT 'pending'
                          CONSTRAINT reservations_status_check
                          CHECK (status IN ('pending','approved','confirmed','started','completed','cancelled','rejected')),
  time_slot       text,
  session_type    text    DEFAULT 'in_person',
  doctor_name     text,
  amount_paid     numeric DEFAULT 0,
  amount_left     numeric,
  branch_id       uuid    REFERENCES public.branches(id) ON DELETE SET NULL,
  customer_id     uuid    REFERENCES public.customers(id) ON DELETE SET NULL,
  room_id         uuid,
  rooms           uuid[]  DEFAULT '{}',
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);
ALTER TABLE public.reservations DISABLE ROW LEVEL SECURITY;

-- If reservations already existed with an old/narrower status constraint, update it
ALTER TABLE public.reservations DROP CONSTRAINT IF EXISTS reservations_status_check;
ALTER TABLE public.reservations ADD CONSTRAINT reservations_status_check
  CHECK (status IN ('pending','approved','confirmed','started','completed','cancelled','rejected'));

-- Ensure all payment and branch columns exist (safe for pre-existing tables)
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS amount_paid  numeric DEFAULT 0;
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS amount_left  numeric;
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS branch_id    uuid REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS customer_id  uuid REFERENCES public.customers(id) ON DELETE SET NULL;


-- 8. ROOMS
CREATE TABLE IF NOT EXISTS public.rooms (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL,
  type        text NOT NULL CHECK (type IN ('clinical', 'administrative')),
  status      text NOT NULL DEFAULT 'available'
              CHECK (status IN ('available', 'on_cleaning', 'needs_cleaning', 'has_issue')),
  branch_id   uuid REFERENCES public.branches(id) ON DELETE CASCADE,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);
ALTER TABLE public.rooms DISABLE ROW LEVEL SECURITY;

-- Ensure room_id and rooms[] columns exist (safe if reservations table pre-existed without them)
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS room_id uuid;
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS rooms   uuid[] DEFAULT '{}';

-- FK from reservations -> rooms (added after rooms table exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'reservations_room_id_fkey'
      AND table_name = 'reservations'
  ) THEN
    ALTER TABLE public.reservations
      ADD CONSTRAINT reservations_room_id_fkey
      FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE SET NULL;
  END IF;
END $$;


-- 9. SERVICE_ROOMS (junction)
CREATE TABLE IF NOT EXISTS public.service_rooms (
  service_id  bigint REFERENCES public.services(id) ON DELETE CASCADE,
  room_id     uuid   REFERENCES public.rooms(id)    ON DELETE CASCADE,
  PRIMARY KEY (service_id, room_id)
);
ALTER TABLE public.service_rooms DISABLE ROW LEVEL SECURITY;

-- Seed rooms and service-room junctions
DO $$
DECLARE
  new_cairo_id uuid;
  zayed_id     uuid;
  room_id_val  uuid;
BEGIN
  SELECT id INTO new_cairo_id FROM public.branches WHERE name_en = 'New Cairo Branch'    LIMIT 1;
  SELECT id INTO zayed_id     FROM public.branches WHERE name_en = 'Sheikh Zayed Branch' LIMIT 1;

  IF new_cairo_id IS NOT NULL THEN
    INSERT INTO public.rooms (name, type, status, branch_id) VALUES
      ('New Cairo Reception',      'administrative', 'available', new_cairo_id),
      ('New Cairo Manager Office', 'administrative', 'available', new_cairo_id),
      ('Laser Room NC 1',          'clinical',       'available', new_cairo_id),
      ('Laser Room NC 2',          'clinical',       'available', new_cairo_id),
      ('Dermatology Room NC 1',    'clinical',       'available', new_cairo_id),
      ('Gynecology Room NC 1',     'clinical',       'available', new_cairo_id),
      ('Physiotherapy Room NC 1',  'clinical',       'available', new_cairo_id)
    ON CONFLICT DO NOTHING;
  END IF;

  IF zayed_id IS NOT NULL THEN
    INSERT INTO public.rooms (name, type, status, branch_id) VALUES
      ('Zayed Reception',          'administrative', 'available', zayed_id),
      ('Zayed Manager Office',     'administrative', 'available', zayed_id),
      ('Laser Room ZY 1',          'clinical',       'available', zayed_id),
      ('Laser Room ZY 2',          'clinical',       'available', zayed_id),
      ('Dermatology Room ZY 1',    'clinical',       'available', zayed_id),
      ('Gynecology Room ZY 1',     'clinical',       'available', zayed_id),
      ('Physiotherapy Room ZY 1',  'clinical',       'available', zayed_id)
    ON CONFLICT DO NOTHING;
  END IF;

  FOR room_id_val IN SELECT id FROM public.rooms WHERE name IN ('Laser Room NC 1','Laser Room NC 2','Laser Room ZY 1','Laser Room ZY 2') LOOP
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (5, room_id_val) ON CONFLICT DO NOTHING;
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (6, room_id_val) ON CONFLICT DO NOTHING;
  END LOOP;

  FOR room_id_val IN SELECT id FROM public.rooms WHERE name IN ('Dermatology Room NC 1','Dermatology Room ZY 1') LOOP
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (1, room_id_val) ON CONFLICT DO NOTHING;
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (2, room_id_val) ON CONFLICT DO NOTHING;
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (3, room_id_val) ON CONFLICT DO NOTHING;
  END LOOP;

  FOR room_id_val IN SELECT id FROM public.rooms WHERE name IN ('Gynecology Room NC 1','Gynecology Room ZY 1') LOOP
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (11, room_id_val) ON CONFLICT DO NOTHING;
  END LOOP;

  FOR room_id_val IN SELECT id FROM public.rooms WHERE name IN ('Physiotherapy Room NC 1','Physiotherapy Room ZY 1') LOOP
    INSERT INTO public.service_rooms (service_id, room_id) VALUES (21, room_id_val) ON CONFLICT DO NOTHING;
  END LOOP;
END $$;

DROP INDEX IF EXISTS public.reservations_unique_room_slot;
CREATE UNIQUE INDEX IF NOT EXISTS reservations_unique_room_slot
  ON public.reservations (room_id, date, time_slot)
  WHERE (status = 'approved' AND room_id IS NOT NULL);


-- 10. PAGE SETTINGS
CREATE TABLE IF NOT EXISTS public.page_settings (
  key         text PRIMARY KEY,
  value       jsonb NOT NULL,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);
ALTER TABLE public.page_settings DISABLE ROW LEVEL SECURITY;


-- 11. ROLES
CREATE TABLE IF NOT EXISTS public.roles (
  id          uuid   PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text   UNIQUE NOT NULL,
  permissions text[] NOT NULL,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to roles"       ON public.roles;
DROP POLICY IF EXISTS "Allow service_role full access to roles" ON public.roles;
DROP POLICY IF EXISTS "Allow public insert to roles"            ON public.roles;
DROP POLICY IF EXISTS "Allow public update to roles"            ON public.roles;
DROP POLICY IF EXISTS "Allow public delete to roles"            ON public.roles;

CREATE POLICY "Allow public read access to roles"       ON public.roles FOR SELECT USING (true);
CREATE POLICY "Allow service_role full access to roles" ON public.roles FOR ALL TO service_role USING (true);
CREATE POLICY "Allow public insert to roles"            ON public.roles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to roles"            ON public.roles FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete to roles"            ON public.roles FOR DELETE USING (true);

INSERT INTO public.roles (name, permissions) VALUES
  ('superadmin',   ARRAY['Bookings','Customers','Providers','Services','Settings']),
  ('admin',        ARRAY['Bookings','Customers','Providers','Services','Settings']),
  ('receptionist', ARRAY['Bookings','Customers'])
ON CONFLICT (name) DO UPDATE SET permissions = EXCLUDED.permissions;


-- 12. EMPLOYEE ACCOUNTS
CREATE TABLE IF NOT EXISTS public.employee_accounts (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id   uuid UNIQUE,
  employee_id    text UNIQUE NOT NULL,
  role_name      text REFERENCES public.roles(name) ON UPDATE CASCADE ON DELETE SET NULL,
  email          text UNIQUE NOT NULL,
  created_at     timestamptz DEFAULT now()
);
ALTER TABLE public.employee_accounts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to employee_accounts"       ON public.employee_accounts;
DROP POLICY IF EXISTS "Allow service_role full access to employee_accounts" ON public.employee_accounts;
DROP POLICY IF EXISTS "Allow public insert to employee_accounts"            ON public.employee_accounts;
DROP POLICY IF EXISTS "Allow public update to employee_accounts"            ON public.employee_accounts;
DROP POLICY IF EXISTS "Allow public delete to employee_accounts"            ON public.employee_accounts;

CREATE POLICY "Allow public read access to employee_accounts"       ON public.employee_accounts FOR SELECT USING (true);
CREATE POLICY "Allow service_role full access to employee_accounts" ON public.employee_accounts FOR ALL TO service_role USING (true);
CREATE POLICY "Allow public insert to employee_accounts"            ON public.employee_accounts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to employee_accounts"            ON public.employee_accounts FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete to employee_accounts"            ON public.employee_accounts FOR DELETE USING (true);


-- ============================================================
-- SCHEMA COMPLETE
-- ============================================================


-- ============================================================
-- LINK YOUR ADMIN USER (run this block separately after
-- creating the user in Supabase Dashboard -> Auth -> Users)
-- ============================================================
-- Replace YOUR-UUID-HERE with the auth user UUID
-- Replace your@email.com with the admin email
-- ============================================================

/*

INSERT INTO public.employee_accounts (auth_user_id, employee_id, role_name, email)
VALUES ('YOUR-UUID-HERE', 'superadmin', 'superadmin', 'your@email.com')
ON CONFLICT (email) DO UPDATE
SET auth_user_id = EXCLUDED.auth_user_id,
    role_name    = EXCLUDED.role_name,
    employee_id  = EXCLUDED.employee_id;

UPDATE auth.users
SET email_confirmed_at = NOW()
WHERE id = 'YOUR-UUID-HERE';

*/
