-- ============================================================
-- Revera Clinics — Database Initialization & Schema Setup
-- Run this in your Dev Supabase SQL Editor (SQL Editor -> New Query)
-- ============================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Branches Table
CREATE TABLE IF NOT EXISTS public.branches (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name_en     text NOT NULL,
  name_ar     text NOT NULL,
  address_en  text NOT NULL,
  address_ar  text NOT NULL,
  phone       text,
  maps_embed  text,
  maps_link   text,
  status      text NOT NULL DEFAULT 'active',
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

-- Seed Default Branches
INSERT INTO public.branches (name_en, name_ar, address_en, address_ar, phone, maps_embed, maps_link, status, sort_order)
VALUES
  (
    'New Cairo Branch',
    'فرع القاهرة الجديدة',
    'Tagamoa, New Cairo, Cairo',
    'التجمع الخامس، القاهرة الجديدة، القاهرة',
    '+201035595691',
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3455.240762823598!2d31.451330111694702!3d30.001242420510955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x145823da15b7dca9%3A0xb388d9b9c32ebce5!2sRevera%20Clinic%20-%20Tagamoa%20Branch!5e0!3m2!1sen!2sit!4v1781634264961!5m2!1sen!2sit',
    'https://maps.app.goo.gl/sXQXDW3A7DdZSRJZ9',
    'active',
    0
  ),
  (
    'Sheikh Zayed Branch',
    'فرع الشيخ زايد',
    'El Nada Clinics Complex, Sheikh Zayed, Giza',
    'مجمع عيادات الندى، الشيخ زايد، الجيزة',
    '+201023122323',
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3452.9529642711104!2d30.9335256!3d30.066882699999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x145859626e72e263%3A0x148f1e87e5c115c0!2sEl%20nada%20CLINICS%20complex!5e0!3m2!1sen!2sit!4v1781634456678!5m2!1sen!2sit',
    'https://maps.app.goo.gl/7ig2Q9iCY9uszyHq9',
    'active',
    1
  )
ON CONFLICT DO NOTHING;

-- 3. Create Services Table
CREATE TABLE IF NOT EXISTS public.services (
  id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  en              text NOT NULL,
  ar              text NOT NULL,
  img             text,
  cat             text,
  unit            text,
  price           numeric NOT NULL DEFAULT 0,
  duration        text,
  description_en  text,
  description_ar  text,
  is_shared       boolean NOT NULL DEFAULT false,
  enable_reminder boolean NOT NULL DEFAULT true,
  branch_pricing  jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order      integer NOT NULL DEFAULT 0,
  visible         boolean NOT NULL DEFAULT true,
  active          boolean NOT NULL DEFAULT true,
  created_at      timestamptz DEFAULT now()
);

-- 4. Create Providers Table
CREATE TABLE IF NOT EXISTS public.providers (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text NOT NULL,
  bookings_count      integer NOT NULL DEFAULT 0,
  services            jsonb NOT NULL DEFAULT '[]'::jsonb,
  more_count          integer NOT NULL DEFAULT 0,
  rating              numeric NOT NULL DEFAULT 0,
  image               text,
  phone               text,
  gender              text,
  age                 integer,
  specialty           text,
  national_id         text,
  working_days_hours  jsonb,
  branch_id           uuid REFERENCES public.branches(id) ON DELETE SET NULL,
  start_date          date,
  created_at          timestamptz DEFAULT now()
);

-- 5. Create Provider Attendance Table
CREATE TABLE IF NOT EXISTS public.provider_attendance (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id  uuid REFERENCES public.providers(id) ON DELETE CASCADE,
  date         date NOT NULL,
  status       text NOT NULL CHECK (status IN ('Present', 'Absent', 'On Leave')),
  check_in     time,
  check_out    time,
  notes        text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now(),
  UNIQUE(provider_id, date)
);

-- 6. Create Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text NOT NULL,
  mobile              text NOT NULL UNIQUE,
  gender              text,
  email               text,
  number_of_bookings  integer DEFAULT 0,
  registration_date   timestamptz DEFAULT now(),
  active              boolean DEFAULT true,
  spent_amount        numeric DEFAULT 0,
  outstanding         numeric DEFAULT 0,
  area                text,
  location_name       text,
  street_name         text,
  building_no         text,
  floor_no            text,
  note                text,
  age                 integer,
  national_id         text,
  address             text,
  referral            text,
  occupation          text,
  created_at          timestamptz DEFAULT now(),
  updated_at          timestamptz DEFAULT now()
);

-- 7. Create Reservations Table
CREATE TABLE IF NOT EXISTS public.reservations (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id      bigint,
  date            text NOT NULL,
  requested_time  text NOT NULL,
  name            text,
  email           text,
  phone           text,
  notes           text,
  status          text NOT NULL DEFAULT 'pending',
  time_slot       text,
  session_type    text,
  doctor_name     text,
  amount_paid     numeric DEFAULT 0,
  amount_left     numeric DEFAULT 0,
  branch_id       uuid REFERENCES public.branches(id) ON DELETE SET NULL,
  customer_id     uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- 8. Create Page Settings Table
CREATE TABLE IF NOT EXISTS public.page_settings (
  key         text PRIMARY KEY,
  value       jsonb NOT NULL,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

-- 9. Create Admin Roles Table
CREATE TABLE IF NOT EXISTS public.roles (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text UNIQUE NOT NULL,
  permissions text[] NOT NULL,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

-- 10. Create Employee Accounts Table
CREATE TABLE IF NOT EXISTS public.employee_accounts (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id   uuid UNIQUE,
  employee_id    text UNIQUE NOT NULL,
  role_name      text REFERENCES public.roles(name) ON UPDATE CASCADE ON DELETE SET NULL,
  email          text UNIQUE NOT NULL,
  created_at     timestamptz DEFAULT now()
);

-- Seed Default Roles
INSERT INTO public.roles (name, permissions)
VALUES 
  ('superadmin', ARRAY['Bookings', 'Customers', 'Providers', 'Services', 'Settings']),
  ('admin', ARRAY['Bookings', 'Customers', 'Providers', 'Services', 'Settings']),
  ('receptionist', ARRAY['Bookings', 'Customers'])
ON CONFLICT (name) DO UPDATE 
SET permissions = EXCLUDED.permissions;

-- Disable Row Level Security (RLS) on public client tables to allow easy client access
ALTER TABLE public.branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_settings DISABLE ROW LEVEL SECURITY;

-- Enable RLS for Roles and Employee Accounts (Authenticated server access only)
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to roles" ON public.roles FOR SELECT USING (true);
CREATE POLICY "Allow service_role full access to roles" ON public.roles FOR ALL TO service_role USING (true);

CREATE POLICY "Allow public read access to employee_accounts" ON public.employee_accounts FOR SELECT USING (true);
CREATE POLICY "Allow service_role full access to employee_accounts" ON public.employee_accounts FOR ALL TO service_role USING (true);
