


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admin_roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "permissions" "text"[]
);


ALTER TABLE "public"."admin_roles" OWNER TO "postgres";


ALTER TABLE "public"."admin_roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."admin_roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."branches" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name_en" "text" NOT NULL,
    "name_ar" "text" NOT NULL,
    "address_en" "text" NOT NULL,
    "address_ar" "text" NOT NULL,
    "phone" "text",
    "maps_embed" "text",
    "maps_link" "text",
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "latitude" numeric,
    "longitude" numeric
);


ALTER TABLE "public"."branches" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."categories" (
    "key" "text" NOT NULL,
    "en" "text" NOT NULL,
    "ar" "text" NOT NULL,
    "sort_order" integer DEFAULT 0
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."customer_product_balances" (
    "id" "text" NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "customer_name" "text",
    "customer_mobile" "text",
    "product_id" "text",
    "product_name" "text" NOT NULL,
    "product_sku" "text",
    "purchased_quantity" numeric DEFAULT 0,
    "used_quantity" numeric DEFAULT 0,
    "remaining_quantity" numeric DEFAULT 0,
    "unit_price" numeric DEFAULT 0,
    "total_amount" numeric DEFAULT 0,
    "status" "text" DEFAULT 'Active'::"text",
    "usage_history" "jsonb" DEFAULT '[]'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "customer_product_balances_status_check" CHECK (("status" = ANY (ARRAY['Active'::"text", 'Depleted'::"text"])))
);


ALTER TABLE "public"."customer_product_balances" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "mobile" "text" NOT NULL,
    "gender" "text",
    "email" "text",
    "number_of_bookings" integer DEFAULT 0,
    "registration_date" timestamp with time zone DEFAULT "now"(),
    "active" boolean DEFAULT true,
    "spent_amount" numeric DEFAULT 0,
    "outstanding" numeric DEFAULT 0,
    "area" "text",
    "location_name" "text",
    "street_name" "text",
    "building_no" "text",
    "floor_no" "text",
    "note" "text",
    "age" integer,
    "national_id" "text",
    "address" "text",
    "referral" "text",
    "occupation" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "wallet_balance" numeric DEFAULT 0
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."device_maintenance_history" (
    "id" "text" NOT NULL,
    "device_id" "text",
    "device_name" "text" NOT NULL,
    "type" "text" DEFAULT 'Pulse Reset'::"text",
    "pulses_added" integer DEFAULT 0,
    "notes" "text",
    "performed_by" "text",
    "date" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."device_maintenance_history" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."doctor_payroll" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "provider_id" "uuid",
    "month" "text" NOT NULL,
    "fixed_salary" numeric DEFAULT 0 NOT NULL,
    "commission_type" "text" DEFAULT 'none'::"text" NOT NULL,
    "commission_value" numeric DEFAULT 0 NOT NULL,
    "completed_services_count" integer DEFAULT 0 NOT NULL,
    "total_commission_earned" numeric DEFAULT 0 NOT NULL,
    "net_salary" numeric DEFAULT 0 NOT NULL,
    "status" "text" DEFAULT 'Draft'::"text" NOT NULL,
    "payment_date" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."doctor_payroll" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."employee_accounts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "auth_user_id" "uuid",
    "employee_id" "text" NOT NULL,
    "role_name" "text",
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text",
    "phone" "text",
    "department" "text" DEFAULT 'Reception'::"text",
    "shift" "text" DEFAULT 'Day'::"text",
    "salary" numeric DEFAULT 0,
    "national_id" "text",
    "national_id_front" "text",
    "national_id_back" "text",
    "address" "text",
    "branch_id" "uuid",
    "contract_file" "text",
    "contract_file_name" "text",
    "required_target_amount" numeric DEFAULT 0,
    "bonus_percentage" numeric DEFAULT 0,
    "target_type" "text" DEFAULT 'reservations'::"text",
    "bonus_type" "text" DEFAULT 'percentage'::"text",
    CONSTRAINT "employee_accounts_bonus_percentage_check" CHECK ((("bonus_percentage" >= (0)::numeric) AND ("bonus_percentage" <= (100)::numeric))),
    CONSTRAINT "employee_accounts_bonus_type_check" CHECK (("bonus_type" = ANY (ARRAY['percentage'::"text", 'fixed'::"text"]))),
    CONSTRAINT "employee_accounts_required_target_amount_check" CHECK (("required_target_amount" >= (0)::numeric)),
    CONSTRAINT "employee_accounts_target_type_check" CHECK (("target_type" = ANY (ARRAY['reservations'::"text", 'revenue'::"text"])))
);


ALTER TABLE "public"."employee_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."employee_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid",
    "note" "text" NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."employee_notes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hr_attendance" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid",
    "date" "date" NOT NULL,
    "check_in_time" timestamp with time zone DEFAULT "now"(),
    "latitude" numeric,
    "longitude" numeric,
    "status" "text" DEFAULT 'Present'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "check_out_time" timestamp with time zone,
    "work_hours" numeric,
    "notes" "text"
);


ALTER TABLE "public"."hr_attendance" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hr_leave_requests" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid",
    "leave_type" "text" NOT NULL,
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "days_count" integer NOT NULL,
    "reason" "text",
    "status" "text" DEFAULT 'Pending'::"text" NOT NULL,
    "approved_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."hr_leave_requests" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hr_missing_alerts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid",
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "resolved" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."hr_missing_alerts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hr_payroll" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid",
    "month" "text" NOT NULL,
    "basic_salary" numeric DEFAULT 0,
    "bonuses" numeric DEFAULT 0,
    "deductions" numeric DEFAULT 0,
    "net_salary" numeric DEFAULT 0,
    "status" "text" DEFAULT 'Draft'::"text" NOT NULL,
    "payment_date" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "target_amount_snapshot" numeric DEFAULT 0,
    "bonus_percentage_snapshot" numeric DEFAULT 0,
    "achieved_revenue" numeric DEFAULT 0,
    "calculated_bonus" numeric DEFAULT 0,
    "target_type_snapshot" "text" DEFAULT 'reservations'::"text",
    "bonus_type_snapshot" "text" DEFAULT 'percentage'::"text"
);


ALTER TABLE "public"."hr_payroll" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hr_performance_reviews" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "employee_id" "uuid",
    "reviewer_id" "uuid",
    "review_date" "date" NOT NULL,
    "rating" integer NOT NULL,
    "comments" "text",
    "goals" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "hr_performance_reviews_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5)))
);


ALTER TABLE "public"."hr_performance_reviews" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."inventory_devices" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "serial_number" "text",
    "model" "text",
    "branch_name" "text",
    "status" "text" DEFAULT 'Active'::"text",
    "total_pulses" integer DEFAULT 0,
    "remaining_pulses" integer DEFAULT 0,
    "max_pulses_limit" integer DEFAULT 0,
    "last_maintenance_date" timestamp with time zone,
    "next_maintenance_date" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."inventory_devices" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."inventory_products" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "sku" "text",
    "category" "text",
    "price" numeric DEFAULT 0,
    "cost_price" numeric DEFAULT 0,
    "stock_quantity" integer DEFAULT 0,
    "min_stock_alert" integer DEFAULT 5,
    "unit" "text" DEFAULT 'pcs'::"text",
    "status" "text" DEFAULT 'In Stock'::"text",
    "branch_name" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."inventory_products" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."medical_records" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "skin_type" "text" DEFAULT 'Normal'::"text",
    "main_concerns" "text"[] DEFAULT '{}'::"text"[],
    "other_concerns_details" "text" DEFAULT ''::"text",
    "has_previous_treatments" boolean DEFAULT false,
    "previous_treatments_details" "text" DEFAULT ''::"text",
    "has_medical_conditions" boolean DEFAULT false,
    "medical_conditions_details" "text" DEFAULT ''::"text",
    "is_taking_medication" boolean DEFAULT false,
    "medication_details" "text" DEFAULT ''::"text",
    "allergies" "text" DEFAULT ''::"text",
    "created_by_role" "text" DEFAULT 'Receptionist'::"text",
    "created_by_name" "text" DEFAULT 'Staff'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."medical_records" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."medical_reports" (
    "id" "text" NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "title" "text" DEFAULT 'Medical Report'::"text",
    "description" "text" DEFAULT ''::"text",
    "file_url" "text",
    "doctor_name" "text" DEFAULT 'Dr. Revera'::"text",
    "date" "date" DEFAULT CURRENT_DATE,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."medical_reports" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."page_settings" (
    "key" "text" NOT NULL,
    "value" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."page_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."prescriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "customer_id" "uuid",
    "patient_name" "text" NOT NULL,
    "date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "diagnosis" "text",
    "medications" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "general_notes" "text",
    "doctor_notes" "text",
    "follow_up_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."prescriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."product_sales" (
    "id" "text" NOT NULL,
    "product_id" "text",
    "product_name" "text" NOT NULL,
    "sku" "text",
    "quantity" integer DEFAULT 1,
    "unit_price" numeric DEFAULT 0,
    "total_price" numeric DEFAULT 0,
    "customer_name" "text",
    "customer_phone" "text",
    "customer_email" "text",
    "cashier_name" "text",
    "branch_name" "text",
    "payment_method" "text" DEFAULT 'Cash'::"text",
    "notes" "text",
    "sale_date" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"(),
    "customer_id" "uuid"
);


ALTER TABLE "public"."product_sales" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."provider_attendance" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "provider_id" "uuid",
    "date" "date" NOT NULL,
    "status" "text" NOT NULL,
    "check_in" time without time zone,
    "check_out" time without time zone,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "provider_attendance_status_check" CHECK (("status" = ANY (ARRAY['Present'::"text", 'Absent'::"text", 'On Leave'::"text"])))
);


ALTER TABLE "public"."provider_attendance" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."provider_schedule_audit_logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "provider_id" "uuid",
    "provider_name" "text" NOT NULL,
    "changed_by" "text" NOT NULL,
    "action" "text" NOT NULL,
    "previous_schedule" "jsonb",
    "new_schedule" "jsonb",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."provider_schedule_audit_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."providers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "bookings_count" integer DEFAULT 0 NOT NULL,
    "services" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "more_count" integer DEFAULT 0 NOT NULL,
    "rating" numeric DEFAULT 0 NOT NULL,
    "image" "text",
    "phone" "text",
    "gender" "text",
    "age" integer,
    "specialty" "text",
    "national_id" "text",
    "working_days_hours" "jsonb",
    "branch_id" "uuid",
    "start_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "fixed_salary" numeric DEFAULT 0 NOT NULL,
    "commission_type" "text" DEFAULT 'none'::"text" NOT NULL,
    "commission_value" numeric DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."providers" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reservations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "service_id" bigint,
    "date" "text" NOT NULL,
    "requested_time" "text" NOT NULL,
    "name" "text",
    "email" "text",
    "phone" "text",
    "notes" "text",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "time_slot" "text",
    "session_type" "text",
    "doctor_name" "text",
    "amount_paid" numeric DEFAULT 0,
    "amount_left" numeric DEFAULT 0,
    "branch_id" "uuid",
    "customer_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "room_id" "uuid",
    "rooms" "uuid"[] DEFAULT '{}'::"uuid"[],
    "service_ids" bigint[] DEFAULT '{}'::bigint[],
    "is_manual" boolean DEFAULT false,
    "created_by_employee_id" "uuid",
    "provider_id" "uuid",
    CONSTRAINT "reservations_status_check" CHECK (("status" = ANY (ARRAY['pending_deposit'::"text", 'pending'::"text", 'approved'::"text", 'confirmed'::"text", 'started'::"text", 'completed'::"text", 'cancelled'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."reservations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "permissions" "text"[] NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rooms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "type" "text" NOT NULL,
    "status" "text" DEFAULT 'available'::"text" NOT NULL,
    "branch_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "rooms_status_check" CHECK (("status" = ANY (ARRAY['available'::"text", 'on_cleaning'::"text", 'needs_cleaning'::"text", 'has_issue'::"text"]))),
    CONSTRAINT "rooms_type_check" CHECK (("type" = ANY (ARRAY['clinical'::"text", 'administrative'::"text"])))
);


ALTER TABLE "public"."rooms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."service_rooms" (
    "service_id" bigint NOT NULL,
    "room_id" "uuid" NOT NULL
);


ALTER TABLE "public"."service_rooms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."services" (
    "id" bigint NOT NULL,
    "en" "text" NOT NULL,
    "ar" "text" NOT NULL,
    "img" "text",
    "cat" "text",
    "unit" "text",
    "price" numeric DEFAULT 0 NOT NULL,
    "duration" "text",
    "description_en" "text",
    "description_ar" "text",
    "is_shared" boolean DEFAULT false NOT NULL,
    "enable_reminder" boolean DEFAULT true NOT NULL,
    "branch_pricing" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "visible" boolean DEFAULT true NOT NULL,
    "active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "duration_minutes" integer,
    CONSTRAINT "services_duration_minutes_check" CHECK ((("duration_minutes" IS NULL) OR (("duration_minutes" > 0) AND ("duration_minutes" <= (24 * 60)))))
);


ALTER TABLE "public"."services" OWNER TO "postgres";


ALTER TABLE "public"."services" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."services_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admin_roles"
    ADD CONSTRAINT "admin_roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."branches"
    ADD CONSTRAINT "branches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."customer_product_balances"
    ADD CONSTRAINT "customer_product_balances_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_mobile_key" UNIQUE ("mobile");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."device_maintenance_history"
    ADD CONSTRAINT "device_maintenance_history_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."doctor_payroll"
    ADD CONSTRAINT "doctor_payroll_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."doctor_payroll"
    ADD CONSTRAINT "doctor_payroll_provider_id_month_key" UNIQUE ("provider_id", "month");



ALTER TABLE ONLY "public"."employee_accounts"
    ADD CONSTRAINT "employee_accounts_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."employee_accounts"
    ADD CONSTRAINT "employee_accounts_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."employee_accounts"
    ADD CONSTRAINT "employee_accounts_employee_id_key" UNIQUE ("employee_id");



ALTER TABLE ONLY "public"."employee_accounts"
    ADD CONSTRAINT "employee_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."employee_notes"
    ADD CONSTRAINT "employee_notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hr_attendance"
    ADD CONSTRAINT "hr_attendance_employee_id_date_key" UNIQUE ("employee_id", "date");



ALTER TABLE ONLY "public"."hr_attendance"
    ADD CONSTRAINT "hr_attendance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hr_leave_requests"
    ADD CONSTRAINT "hr_leave_requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hr_missing_alerts"
    ADD CONSTRAINT "hr_missing_alerts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hr_payroll"
    ADD CONSTRAINT "hr_payroll_employee_id_month_key" UNIQUE ("employee_id", "month");



ALTER TABLE ONLY "public"."hr_payroll"
    ADD CONSTRAINT "hr_payroll_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hr_performance_reviews"
    ADD CONSTRAINT "hr_performance_reviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_devices"
    ADD CONSTRAINT "inventory_devices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."inventory_products"
    ADD CONSTRAINT "inventory_products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."medical_records"
    ADD CONSTRAINT "medical_records_customer_id_key" UNIQUE ("customer_id");



ALTER TABLE ONLY "public"."medical_records"
    ADD CONSTRAINT "medical_records_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."medical_reports"
    ADD CONSTRAINT "medical_reports_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."page_settings"
    ADD CONSTRAINT "page_settings_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."prescriptions"
    ADD CONSTRAINT "prescriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."product_sales"
    ADD CONSTRAINT "product_sales_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."provider_attendance"
    ADD CONSTRAINT "provider_attendance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."provider_attendance"
    ADD CONSTRAINT "provider_attendance_provider_id_date_key" UNIQUE ("provider_id", "date");



ALTER TABLE ONLY "public"."provider_schedule_audit_logs"
    ADD CONSTRAINT "provider_schedule_audit_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."providers"
    ADD CONSTRAINT "providers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rooms"
    ADD CONSTRAINT "rooms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."service_rooms"
    ADD CONSTRAINT "service_rooms_pkey" PRIMARY KEY ("service_id", "room_id");



ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "services_pkey" PRIMARY KEY ("id");



CREATE INDEX "product_sales_customer_id_idx" ON "public"."product_sales" USING "btree" ("customer_id");



CREATE INDEX "product_sales_sale_date_idx" ON "public"."product_sales" USING "btree" ("sale_date");



CREATE INDEX "reservations_branch_date_idx" ON "public"."reservations" USING "btree" ("branch_id", "date");



CREATE INDEX "reservations_date_status_idx" ON "public"."reservations" USING "btree" ("date", "status");



CREATE INDEX "reservations_provider_id_idx" ON "public"."reservations" USING "btree" ("provider_id");



CREATE UNIQUE INDEX "reservations_unique_room_slot" ON "public"."reservations" USING "btree" ("room_id", "date", "time_slot") WHERE (("status" = 'approved'::"text") AND ("room_id" IS NOT NULL));



ALTER TABLE ONLY "public"."customer_product_balances"
    ADD CONSTRAINT "customer_product_balances_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."device_maintenance_history"
    ADD CONSTRAINT "device_maintenance_history_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "public"."inventory_devices"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."doctor_payroll"
    ADD CONSTRAINT "doctor_payroll_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."employee_accounts"
    ADD CONSTRAINT "employee_accounts_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."employee_accounts"
    ADD CONSTRAINT "employee_accounts_role_name_fkey" FOREIGN KEY ("role_name") REFERENCES "public"."roles"("name") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."employee_notes"
    ADD CONSTRAINT "employee_notes_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."employee_accounts"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."employee_notes"
    ADD CONSTRAINT "employee_notes_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hr_attendance"
    ADD CONSTRAINT "hr_attendance_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hr_leave_requests"
    ADD CONSTRAINT "hr_leave_requests_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "public"."employee_accounts"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."hr_leave_requests"
    ADD CONSTRAINT "hr_leave_requests_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hr_missing_alerts"
    ADD CONSTRAINT "hr_missing_alerts_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hr_payroll"
    ADD CONSTRAINT "hr_payroll_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hr_performance_reviews"
    ADD CONSTRAINT "hr_performance_reviews_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hr_performance_reviews"
    ADD CONSTRAINT "hr_performance_reviews_reviewer_id_fkey" FOREIGN KEY ("reviewer_id") REFERENCES "public"."employee_accounts"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."medical_records"
    ADD CONSTRAINT "medical_records_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."medical_reports"
    ADD CONSTRAINT "medical_reports_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."prescriptions"
    ADD CONSTRAINT "prescriptions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."product_sales"
    ADD CONSTRAINT "product_sales_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."product_sales"
    ADD CONSTRAINT "product_sales_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."inventory_products"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."provider_attendance"
    ADD CONSTRAINT "provider_attendance_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."provider_schedule_audit_logs"
    ADD CONSTRAINT "provider_schedule_audit_logs_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."providers"
    ADD CONSTRAINT "providers_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_created_by_employee_id_fkey" FOREIGN KEY ("created_by_employee_id") REFERENCES "public"."employee_accounts"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."rooms"
    ADD CONSTRAINT "rooms_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "public"."branches"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."service_rooms"
    ADD CONSTRAINT "service_rooms_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."service_rooms"
    ADD CONSTRAINT "service_rooms_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE CASCADE;



CREATE POLICY "Allow all access to device_maintenance_history" ON "public"."device_maintenance_history" USING (true);



CREATE POLICY "Allow all access to inventory_devices" ON "public"."inventory_devices" USING (true);



CREATE POLICY "Allow all access to inventory_products" ON "public"."inventory_products" USING (true);



CREATE POLICY "Allow all access to product_sales" ON "public"."product_sales" USING (true);



CREATE POLICY "Allow public delete to employee_accounts" ON "public"."employee_accounts" FOR DELETE USING (true);



CREATE POLICY "Allow public delete to roles" ON "public"."roles" FOR DELETE USING (true);



CREATE POLICY "Allow public insert to employee_accounts" ON "public"."employee_accounts" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert to roles" ON "public"."roles" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public read access to employee_accounts" ON "public"."employee_accounts" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to employee_notes" ON "public"."employee_notes" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to hr_attendance" ON "public"."hr_attendance" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to hr_leave_requests" ON "public"."hr_leave_requests" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to hr_missing_alerts" ON "public"."hr_missing_alerts" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to hr_payroll" ON "public"."hr_payroll" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to hr_performance_reviews" ON "public"."hr_performance_reviews" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to prescriptions" ON "public"."prescriptions" FOR SELECT USING (true);



CREATE POLICY "Allow public read access to roles" ON "public"."roles" FOR SELECT USING (true);



CREATE POLICY "Allow public update to employee_accounts" ON "public"."employee_accounts" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Allow public update to roles" ON "public"."roles" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Allow public write access to employee_notes" ON "public"."employee_notes" USING (true);



CREATE POLICY "Allow public write access to hr_attendance" ON "public"."hr_attendance" USING (true);



CREATE POLICY "Allow public write access to hr_leave_requests" ON "public"."hr_leave_requests" USING (true);



CREATE POLICY "Allow public write access to hr_missing_alerts" ON "public"."hr_missing_alerts" USING (true);



CREATE POLICY "Allow public write access to hr_payroll" ON "public"."hr_payroll" USING (true);



CREATE POLICY "Allow public write access to hr_performance_reviews" ON "public"."hr_performance_reviews" USING (true);



CREATE POLICY "Allow public write access to prescriptions" ON "public"."prescriptions" USING (true);



CREATE POLICY "Allow service_role full access to employee_accounts" ON "public"."employee_accounts" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to employee_notes" ON "public"."employee_notes" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to hr_attendance" ON "public"."hr_attendance" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to hr_leave_requests" ON "public"."hr_leave_requests" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to hr_missing_alerts" ON "public"."hr_missing_alerts" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to hr_payroll" ON "public"."hr_payroll" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to hr_performance_reviews" ON "public"."hr_performance_reviews" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to prescriptions" ON "public"."prescriptions" TO "service_role" USING (true);



CREATE POLICY "Allow service_role full access to roles" ON "public"."roles" TO "service_role" USING (true);



ALTER TABLE "public"."admin_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."branches" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customer_product_balances" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."device_maintenance_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."doctor_payroll" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."employee_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."employee_notes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hr_attendance" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hr_leave_requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hr_missing_alerts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hr_payroll" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hr_performance_reviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory_devices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."inventory_products" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."medical_records" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."medical_reports" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."page_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."prescriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."product_sales" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."provider_attendance" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."provider_schedule_audit_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."providers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reservations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rooms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."service_rooms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."admin_roles" TO "anon";
GRANT ALL ON TABLE "public"."admin_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."admin_roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."admin_roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admin_roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admin_roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."branches" TO "anon";
GRANT ALL ON TABLE "public"."branches" TO "authenticated";
GRANT ALL ON TABLE "public"."branches" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."customer_product_balances" TO "anon";
GRANT ALL ON TABLE "public"."customer_product_balances" TO "authenticated";
GRANT ALL ON TABLE "public"."customer_product_balances" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON TABLE "public"."device_maintenance_history" TO "anon";
GRANT ALL ON TABLE "public"."device_maintenance_history" TO "authenticated";
GRANT ALL ON TABLE "public"."device_maintenance_history" TO "service_role";



GRANT ALL ON TABLE "public"."doctor_payroll" TO "anon";
GRANT ALL ON TABLE "public"."doctor_payroll" TO "authenticated";
GRANT ALL ON TABLE "public"."doctor_payroll" TO "service_role";



GRANT ALL ON TABLE "public"."employee_accounts" TO "anon";
GRANT ALL ON TABLE "public"."employee_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."employee_notes" TO "anon";
GRANT ALL ON TABLE "public"."employee_notes" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_notes" TO "service_role";



GRANT ALL ON TABLE "public"."hr_attendance" TO "anon";
GRANT ALL ON TABLE "public"."hr_attendance" TO "authenticated";
GRANT ALL ON TABLE "public"."hr_attendance" TO "service_role";



GRANT ALL ON TABLE "public"."hr_leave_requests" TO "anon";
GRANT ALL ON TABLE "public"."hr_leave_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."hr_leave_requests" TO "service_role";



GRANT ALL ON TABLE "public"."hr_missing_alerts" TO "anon";
GRANT ALL ON TABLE "public"."hr_missing_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."hr_missing_alerts" TO "service_role";



GRANT ALL ON TABLE "public"."hr_payroll" TO "anon";
GRANT ALL ON TABLE "public"."hr_payroll" TO "authenticated";
GRANT ALL ON TABLE "public"."hr_payroll" TO "service_role";



GRANT ALL ON TABLE "public"."hr_performance_reviews" TO "anon";
GRANT ALL ON TABLE "public"."hr_performance_reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."hr_performance_reviews" TO "service_role";



GRANT ALL ON TABLE "public"."inventory_devices" TO "anon";
GRANT ALL ON TABLE "public"."inventory_devices" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory_devices" TO "service_role";



GRANT ALL ON TABLE "public"."inventory_products" TO "anon";
GRANT ALL ON TABLE "public"."inventory_products" TO "authenticated";
GRANT ALL ON TABLE "public"."inventory_products" TO "service_role";



GRANT ALL ON TABLE "public"."medical_records" TO "anon";
GRANT ALL ON TABLE "public"."medical_records" TO "authenticated";
GRANT ALL ON TABLE "public"."medical_records" TO "service_role";



GRANT ALL ON TABLE "public"."medical_reports" TO "anon";
GRANT ALL ON TABLE "public"."medical_reports" TO "authenticated";
GRANT ALL ON TABLE "public"."medical_reports" TO "service_role";



GRANT ALL ON TABLE "public"."page_settings" TO "anon";
GRANT ALL ON TABLE "public"."page_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."page_settings" TO "service_role";



GRANT ALL ON TABLE "public"."prescriptions" TO "anon";
GRANT ALL ON TABLE "public"."prescriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."prescriptions" TO "service_role";



GRANT ALL ON TABLE "public"."product_sales" TO "anon";
GRANT ALL ON TABLE "public"."product_sales" TO "authenticated";
GRANT ALL ON TABLE "public"."product_sales" TO "service_role";



GRANT ALL ON TABLE "public"."provider_attendance" TO "anon";
GRANT ALL ON TABLE "public"."provider_attendance" TO "authenticated";
GRANT ALL ON TABLE "public"."provider_attendance" TO "service_role";



GRANT ALL ON TABLE "public"."provider_schedule_audit_logs" TO "anon";
GRANT ALL ON TABLE "public"."provider_schedule_audit_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."provider_schedule_audit_logs" TO "service_role";



GRANT ALL ON TABLE "public"."providers" TO "anon";
GRANT ALL ON TABLE "public"."providers" TO "authenticated";
GRANT ALL ON TABLE "public"."providers" TO "service_role";



GRANT ALL ON TABLE "public"."reservations" TO "anon";
GRANT ALL ON TABLE "public"."reservations" TO "authenticated";
GRANT ALL ON TABLE "public"."reservations" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON TABLE "public"."rooms" TO "anon";
GRANT ALL ON TABLE "public"."rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."rooms" TO "service_role";



GRANT ALL ON TABLE "public"."service_rooms" TO "anon";
GRANT ALL ON TABLE "public"."service_rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."service_rooms" TO "service_role";



GRANT ALL ON TABLE "public"."services" TO "anon";
GRANT ALL ON TABLE "public"."services" TO "authenticated";
GRANT ALL ON TABLE "public"."services" TO "service_role";



GRANT ALL ON SEQUENCE "public"."services_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
